security:
    password_hashers:
        App\User\Infrastructure\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\User\Infrastructure\Entity\User
                property: phoneNumber

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: phoneNumber
                password_parameter: password

            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/logout, roles: PUBLIC_ACCESS }
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }

