user_controllers:
    resource: '../src/User/Infrastructure/Controller'
    type: attribute
    prefix: /user

home_controllers:
    resource: '../src/Core/UI/Controller'
    type: attribute

Test_controllers:
    resource: '../src/Test/Infrastructure/Controller'
    type: attribute

