# config/services.yaml

parameters:
# Tes paramètres ici si besoin

services:
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Configuration automatique des services
        public: false       # Les services sont privés par défaut

    # Chargement des classes de src/ en services (excluant entités, controllers, etc.)
    App\:
        resource: '../src/'
        exclude:
            - '../src/Kernel.php'
            - '../src/**/Domain/Entity/'
            - '../src/**/Domain/ValueObject/'
            - '../src/**/Application/DTO/'
            - '../src/**/Infrastructure/Entity/'
            - '../src/**/UI/Controller/'

    # Configuration explicite des controllers (pour routing etc.)
    App\Core\UI\Controller\:
        resource: '../src/Core/UI/Controller/'
        tags: ['controller.service_arguments']

    App\User\Infrastructure\Controller\:
        resource: '../src/User/Infrastructure/Controller/'
        tags: ['controller.service_arguments']

    App\Test\Infrastructure\Controller\:
        resource: '../src/Test/Infrastructure/Controller/'
        tags: ['controller.service_arguments']

    # Alias pour les interfaces vers leurs implémentations concrètes

    # User repository
    App\User\Domain\Repository\UserRepositoryInterface:
        alias: App\User\Infrastructure\Repository\UserRepository

    # Question repository — important pour ton erreur
    App\Test\Domain\Repository\QuestionRepositoryInterface:
        alias: App\Test\Infrastructure\Repository\QuestionPersonalityDoctrineRepository

    # Si tu veux aussi les autres, mais ce sont des classes concrètes, pas des interfaces
    App\Test\Domain\Repository\QuestionDoctrineRepository:
        alias: App\Test\Infrastructure\Repository\QuestionDoctrineRepository

    App\Test\Domain\Repository\QuestionPersonalityDoctrineRepository:
        alias: App\Test\Infrastructure\Repository\QuestionPersonalityDoctrineRepository

    App\Test\Domain\Repository\TestPersonalityRepository:
        alias: App\Test\Infrastructure\Repository\TestPersonalityRepository

    # Service pour la lecture des annotations (souvent nécessaire)
    annotation_reader:
        class: Doctrine\Common\Annotations\AnnotationReader
        public: false

    # Ajoute ici d’autres services explicites si besoin

